# Generated by Django 5.0.6 on 2024-06-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMinderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='description',
        ),
    ]
