# Generated by Django 5.0.6 on 2024-06-21 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMinderApp', '0002_rename_name_expense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='priority',
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(default=datetime.datetime(2024, 6, 21, 13, 58, 42, 886601, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('unimportant', 'Unimportant'), ('entertainment', 'Entertainment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(),
        ),
    ]
