# Generated by Django 5.0.6 on 2024-06-22 05:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMinderApp', '0003_remove_reminder_name_remove_wishlist_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 6, 22, 5, 18, 3, 756071, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('unimportant', 'Unimportant')], max_length=20),
        ),
    ]
