# Generated by Django 5.0.6 on 2024-06-22 05:29

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMinderApp', '0004_rename_price_wishlist_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Savings',
            new_name='Saving',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='description',
            field=models.CharField(default=datetime.datetime(2024, 6, 22, 5, 29, 0, 592957, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('unimportant', 'Unimportant')], max_length=50),
        ),
    ]
