# Generated by Django 5.0.6 on 2024-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMinderApp', '0005_rename_savings_saving_remove_expense_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('unimportant', 'Unimportant')], max_length=20),
        ),
    ]
