# Generated by Django 5.0.6 on 2024-06-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMinderApp', '0006_alter_budget_amount_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('important', 'Important'), ('unimportant', 'Unimportant')], max_length=50),
        ),
    ]
